#taken from https://gitlab.computing.dcu.ie/sblott/test-project-android/blob/master/.gitlab-ci.yml

image: smblott/dcu-docker-gitlab-ci

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "29.0.2"

stages:
  - pre
  - build
  - test

context:
  stage: pre
  script:
    - env | grep CACHE
    - echo $ANDROID_HOME
    - ls -l $ANDROID_HOME

assembleDebug:
  stage: build
  script:
    - sh src/GymVisionAndroid/script/run-gradle.sh assembleDebug
  artifacts:
    paths:
    - src/GymVisionAndroid/src/app/build/outputs/

lint:
  stage: test
  script:
    - sh src/GymVisionAndroid/script/run-gradle.sh -Pci --console=plain :app:lintDebug -PbuildDir=lint

debugTests:
  stage: test
  script:
    - sh src/GymVisionAndroid/script/run-gradle.sh -Pci --console=plain :app:testDebug

unitTests:
  stage: test
  script:
    - sh src/GymVisionAndroid/script/run-gradle.sh test

pythontests:
  stage: test
  script:
    - "python src/GymVisionDesktop/python-unittests.py"
